name: Hydraulic Hose akron-ohio
favicon: null
layout_spectrum: 1
typography_spectrum: 0.38995
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000010'
    - '#fffeff'
    - '#adc897'
    - '#249b9d'
    - '#424142'
  brandStrength: 0.3313944903202355
  lightness: 0.6622002141084522
  saturation: 0.2111233330797404
  rhythmicContrast: 0.9914702556561679
purpose: []
